#!/usr/bin/env ruby

# Copyright (c) 2011 Grayson Manley
# Licensed under the MIT license: http://www.opensource.org/licenses/mit-license
input = $stdin.gets
args = input.split(" ")
old_head_ref = args[0]
new_head_ref = args[1]

require 'rubygems'
require 'accuhook'

repository = Grit::Repo.new(File.join(File.dirname(__FILE__), "..", "..", ".."))

@commits = []
repository.commit_deltas_from(repository, old_head_ref, new_head_ref).each do |commit|
  @commits << commit
end

AccuHook::Accurev::Commit.new(repository, @commits.reverse)