#!/usr/bin/env ruby

input = $stdin.gets
args = input.split(" ")
old_head_ref = args[0]
new_head_ref = args[1]

begin; require 'rubygems'; rescue LoadError; end # Needed? Since git will be calling this file I dunno what the ENV is like.
require 'legit-the-git'

repository = Grit::Repo.new(File.join(File.dirname(__FILE__), "..", "..", ".."))

@commits = []
repository.commit_deltas_from(repository, old_head_ref, new_head_ref).each do |commit|
  @commits << commit
end

LegitGit::Commit.new(repository, @commits.reverse)